"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// import {Customer} from './class';
// let myCustomer = new Customer("Martin", "Dixon");
// console.log(myCustomer.firstName);
// console.log(myCustomer.lastName);
const Shape_1 = require("./Shape");
const Circle_1 = require("./Circle");
const Rectangle_1 = require("./Rectangle");
let myShape = new Shape_1.Shape(10, 15);
console.log(myShape.getInfo());
let myCircle = new Circle_1.Circle(5, 10, 20);
console.log(myCircle.getInfo());
let myRectangle = new Rectangle_1.Rectangle(0, 0, 3, 7);
console.log(myRectangle.getInfo());
